---
- name: "Debian: Create admin account"
  when: ansible_os_family == "Debian"
  sudo: yes
  user:
    state: present
    name: "{{ admin_user }}"
    password: "{{ admin_password }}"
    comment: "{{ admin_comment }}"
    append: yes
    groups: sudo,admin
  tags:
    - accounts
    - debian
- name: sudo group as sudoers
  when: ansible_os_family == "Debian"
  sudo: yes
  lineinfile:
    destfile: /etc/sudoers
    backup: yes
  line: "%sudo        ALL=(ALL:ALL)"
  regexp: "^#?\s*%sudo"
- name: "RedHat: Create admin account"
  when: ansible_os_family == "RedHat"
  sudo: yes
  user:
    state: present
    name: "{{ admin_user }}"
    password: "{{ admin_password }}"
    comment: "{{ admin_comment }}"
    append: yes
    groups: wheel
  tags:
    - accounts
    - redhat
- name: wheel group as sudoers
  when: ansible_os_family == "RedHat"
  sudo: yes
  lineinfile:
    destfile: /etc/sudoers
    backup: yes
  line: "%wheel        ALL=(ALL)       NOPASSWD: ALL"
  regexp: "^#?\s*%wheel"
